[project]
name = "spost"
version = "0.1.0"
description = ""
authors = [
    {name = "Panos Mavrogiorgos",email = "pmav99@gmail.com"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "xarray",
    "natsort",
    "numpy",
    "multifutures[full]",
    "zarr",
    "cyclopts",
    "dask",
    "shapely",
    "numpy-indexed",
    "pytmd"
]


[project.scripts]
spost = "spost.__main__:main"

[project.optional-dependencies]
image = ["pillow", "colorcet", "datashader"]
complete = [
    "pillow",
    "colorcet",
    "datashader",
    "netcdf4",
    "dask",
    "searvey",
    "seastats",
    "joblib",
    "matplotlib",
    "jinja2",
    "pyarrow",
    "pandas",
    "netcdf4",
    "pytides2 @ git+https://github.com/tomsail/pytides.git",
    "ioc-cleanup @ git+https://github.com/tomsail/ioc_cleanup.git",
    "pytmd"
]
schism = ["netcdf4", "dask"]
validate = [
    "searvey",
    "seastats",
    "joblib",
    "matplotlib",
    "jinja2",
    "pyarrow",
    "pandas",
    "netcdf4",
    "pytides2 @ git+https://github.com/tomsail/pytides.git",
    "ioc-cleanup @ git+https://github.com/tomsail/ioc_cleanup.git",
]
tide = ["pytmd"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
include = [{ path = "spost/regions/*.wkt", format = ["sdist", "wheel"] }]

[tool.poetry.group.dev.dependencies]
ipykernel = "*"
pytest = "*"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
